export enum ErrorCode {
  RUN_NOT_FOUND = 'RUN_NOT_FOUND',
  INVALID_STATE_TRANSITION = 'INVALID_STATE_TRANSITION',
  RUNTIME_UNAVAILABLE = 'RUNTIME_UNAVAILABLE',
  RUNTIME_TIMEOUT = 'RUNTIME_TIMEOUT',
  STREAM_EXHAUSTED = 'STREAM_EXHAUSTED',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  MODE_NOT_SUPPORTED = 'MODE_NOT_SUPPORTED',
  CIRCUIT_BREAKER_OPEN = 'CIRCUIT_BREAKER_OPEN',
  INVALID_SESSION_ID = 'INVALID_SESSION_ID',
  UNKNOWN_POLICY_VERSION = 'UNKNOWN_POLICY_VERSION',
  POLICY_DENIED = 'POLICY_DENIED',
  INVALID_POLICY_DEFINITION = 'INVALID_POLICY_DEFINITION',
  SESSION_ALREADY_EXISTS = 'SESSION_ALREADY_EXISTS',
  // Generic codes used when translating a downstream gRPC status into an HTTP
  // response (see `mapGrpcError`). Kept distinct from the domain-specific codes
  // above so clients can branch on the transport-level cause.
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
  RATE_LIMITED = 'RATE_LIMITED'
}
