export enum ErrorCode {
  RUN_NOT_FOUND = 'RUN_NOT_FOUND',
  INVALID_STATE_TRANSITION = 'INVALID_STATE_TRANSITION',
  RUNTIME_UNAVAILABLE = 'RUNTIME_UNAVAILABLE',
  RUNTIME_TIMEOUT = 'RUNTIME_TIMEOUT',
  STREAM_EXHAUSTED = 'STREAM_EXHAUSTED',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  MODE_NOT_SUPPORTED = 'MODE_NOT_SUPPORTED',
  CIRCUIT_BREAKER_OPEN = 'CIRCUIT_BREAKER_OPEN',
  INVALID_SESSION_ID = 'INVALID_SESSION_ID',
  UNKNOWN_POLICY_VERSION = 'UNKNOWN_POLICY_VERSION',
  POLICY_DENIED = 'POLICY_DENIED',
  INVALID_POLICY_DEFINITION = 'INVALID_POLICY_DEFINITION',
  SESSION_ALREADY_EXISTS = 'SESSION_ALREADY_EXISTS'
}
